name: CI Checks
run-name: Running Terraform Checks by ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  Initial-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Getting initiator name
        run: echo "Workflow initiated by ${{ github.actor }} from branch ${{ github.ref_name }}"

  terraform-checks:
    runs-on: ubuntu-latest
    needs: Initial-Checks
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
             tflint --disable-rule=terraform_module_version \
             --disable-rule=terraform_required_providers \
             --disable-rule=terraform_required_version


      - name: Run TFLint
        run: tflint -f compact

  snyk-checks:
    runs-on: ubuntu-latest
    needs: terraform-checks
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan
        run: snyk code test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Scan
        run: snyk test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk IaC Scan
        run: snyk iac test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  summary:
    needs: [terraform-checks, snyk-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown summary
        run: |
          TF_STATUS=${{ needs.terraform-checks.outputs.status }}
          SNYK_STATUS=${{ needs.snyk-checks.outputs.status }}

          echo '## 🚀 Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '| Job Name         | Status |' >> $GITHUB_STEP_SUMMARY
          echo '|------------------|--------|' >> $GITHUB_STEP_SUMMARY
          echo "| Terraform Checks | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| Snyk Scans       | $SNYK_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo "## Job initiated by: **${{ github.actor }}**" >> $GITHUB_STEP_SUMMARY
